### ISSUE TITLE
Add method to pull all organizations accounts holders and its token balance

### ISSUE THREAD

**Issue by delfipolito** [aragonone/token-wrapper#3]
In this screen we should be able to see not only the connected account holder, but all organization holders
![image](https://user-images.githubusercontent.com/10419340/67042856-246d9980-f0ff-11e9-98b5-05585d2a7b8a.png)

**Comment by eternauta1337** [comment]
Fixed in [this commit](https://github.com/aragonone/token-wrapper/commit/b08dbabc510c971324eed3643c0de20b590be481) in the ui-frontend branch.
