### ISSUE TITLE
Signature dosnt appear to be the same as the version on apm

### ISSUE THREAD

**Issue by AaronAbuUsama** [aragonone/token-wrapper#54]
the initialise function in this repo says it accepts an `(address, string, string)` so I expect the app to install with 

```
dao install $dao token-wrapper.open.aragonpm.eth --app-init-args $flf "FLF"  $flags      
``` 
```
dao install 0x0726b12d478d72eDA97c344d8bF91F42D134f39c token-wrapper.open.aragonpm.eth --app-init-args 0xcbe9c2cbf8a87F2982689B4acb805e9a94c42340 FLF FLF --environment aragon:rinkeby --use-frame
```
where `$flf` is the regular erc20 token to wrap

however, I get this error
```
  ✖ Deploying app instance
    → invalid address (arg="_erc20", coderType="address", value="FLF")
    Fetching deployed app
✖ Invalid initialization params for app. Check the arguments passed with the --app-init-args flag
invalid address (arg="_erc20", coderType="address", value="FLF")
```
I'm guessing the first arg is probably the wrapped token so after creating a minime token and replacing the first param I get a transaction path error. this is a custom deploy and my account has the `app manager` and `create permissions` role

https://github.com/aragonone/voting-connectors/blob/4e69dbf0006df69b41be5468382dbac7ff0c37ad/apps/token-wrapper/contracts/TokenWrapper.sol#L62

**Comment by sohkai** [comment]
Ah, the versions deployed on `open` and `hatch` are different. The `open` deployment should be treated as deprecated (we currently don't have a way to do this, but could be added via the published metadata).

`token-wrapper.hatch.aragonpm.eth` should have the correct, documented signature.

-----

In any case, it's been a long-standing todo to re-organize the documentation in this repo to better provide details like this and where the canonical deployment is.
